86b2j5p5v-venue-cards-poc: Venue cards with image carousel POC
tracet2t/Venue-Reservation pull request #3
Opened 2024-10-21 14:27 UTC by LakshananS

The carousel implementation in the provided code is a simple image slider component built using Next.js. It displays a series of images with smooth transitions between slides.

2024-10-22 17:20 UTC, bsaranga requested changes
Make requested changes.

2024-10-22 17:20 UTC, bsaranga commented on venue-reservation/src/Components/Carousel/page.tsx
Let's use lower case directory and file names as a convention. Remove the folder named `Carousel` and rename `page.tsx` as `carousel.tsx` and rename `Component` to `component` and move `carousel.tsx` to `component.tsx`. Final dir structure should be `src/components/carousel.tsx`.

2024-10-22 18:55 UTC, LakshananS commented on venue-reservation/src/Components/Carousel/page.tsx
I re-named and updated folders and file name.

2024-10-23 12:01 UTC, bsaranga commented
@LakshananS Overall good, let's make the carousel component customizable by passing in props fo r container width, height, next/prev arrow colors, and dot indicator colors:

Props to be passed:
`width`
`height`
`arrow_bg_color`
`arrow_fg_color`
`dot_color`

2024-10-23 14:29 UTC, LakshananS commented
* The Carousel component now accepts customizable props (width, height, arrowBgColor, arrowFgColor, dotColor, and activeDotColor).

* Each VenueCard can now pass different styles and sizes to the Carousel, making it reusable for multiple layouts and designs.

2024-10-23 15:03 UTC, bsaranga approved these changes

2024-10-23 15:03 UTC, merged